name: Run flake tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  flake-check:
    name: Flake checks (${{ matrix.system }})
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - system: aarch64-darwin
            runner: macos-latest
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
          - system: x86_64-linux
            runner: ubuntu-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Run flake checks
        run: nix flake check --system ${{ matrix.system }}
